routes/admin.php
<?php

/*
  |--------------------------------------------------------------------------
  | Admin Routes
  |--------------------------------------------------------------------------
  |
 */

Route::get('index/panel', 'Strongadmin\IndexController@panel'); //面板
//上传
Route::post('upload/image', 'Common\UploadController@image'); //上传图片
Route::post('upload/image/wangeditor', 'Common\UploadController@imageWangEditor'); //富文本图片上传【wangEditor】
//产品管理
Route::any('product/index', 'Strongadmin\Product\ProductController@index');
Route::any('product/show', 'Strongadmin\Product\ProductController@show');
Route::any('product/create', 'Strongadmin\Product\ProductController@create')->name('product.create');
Route::any('product/update', 'Strongadmin\Product\ProductController@update');
Route::any('product/destroy', 'Strongadmin\Product\ProductController@destroy');
Route::any('product/copy', 'Strongadmin\Product\ProductController@copy');
Route::any('product/spec/htmlString', 'Strongadmin\Product\ProductController@specHtmlString');
//产品分类
Route::any('product/category/index', 'Strongadmin\Product\CategoryController@index');
Route::any('product/category/show', 'Strongadmin\Product\CategoryController@show');
Route::any('product/category/create', 'Strongadmin\Product\CategoryController@create');
Route::any('product/category/update', 'Strongadmin\Product\CategoryController@update');
Route::any('product/category/destroy', 'Strongadmin\Product\CategoryController@destroy');
//产品规格组
Route::any('product/specGroup/index', 'Strongadmin\Product\SpecGroupController@index');
Route::any('product/specGroup/show', 'Strongadmin\Product\SpecGroupController@show');
Route::any('product/specGroup/create', 'Strongadmin\Product\SpecGroupController@create');
Route::any('product/specGroup/update', 'Strongadmin\Product\SpecGroupController@update');
Route::any('product/specGroup/destroy', 'Strongadmin\Product\SpecGroupController@destroy');
//产品规格
Route::any('product/spec/index', 'Strongadmin\Product\SpecController@index');
Route::any('product/spec/show', 'Strongadmin\Product\SpecController@show');
Route::any('product/spec/create', 'Strongadmin\Product\SpecController@create');
Route::any('product/spec/update', 'Strongadmin\Product\SpecController@update');
Route::any('product/spec/destroy', 'Strongadmin\Product\SpecController@destroy');
//产品品牌
Route::any('product/brand/index', 'Strongadmin\Product\BrandController@index');
Route::any('product/brand/show', 'Strongadmin\Product\BrandController@show');
Route::any('product/brand/create', 'Strongadmin\Product\BrandController@create');
Route::any('product/brand/update', 'Strongadmin\Product\BrandController@update');
Route::any('product/brand/destroy', 'Strongadmin\Product\BrandController@destroy');
//订单管理
Route::any('order/index', 'Strongadmin\OrderController@index');
Route::any('order/show', 'Strongadmin\OrderController@show');
Route::any('order/create', 'Strongadmin\OrderController@create');
Route::any('order/update', 'Strongadmin\OrderController@update');
Route::any('order/destroy', 'Strongadmin\OrderController@destroy');
Route::any('order/confirm/close', 'Strongadmin\OrderController@close'); //确认关闭
Route::any('order/confirm/paid', 'Strongadmin\OrderController@confirmPaid'); //确认已付款
Route::any('order/confirm/shipped', 'Strongadmin\OrderController@confirmShipped'); //确认发货
Route::any('order/confirm/returned', 'Strongadmin\OrderController@confirmReturned'); //确认已退货
Route::any('order/confirm/done', 'Strongadmin\OrderController@confirmDone'); //确认已完成
Route::any('order/products', 'Strongadmin\OrderController@products'); //订单产品
Route::any('order/print', 'Strongadmin\OrderController@print'); //打印
//会员管理
Route::any('user/index', 'Strongadmin\User\UserController@index');
Route::any('user/show', 'Strongadmin\User\UserController@show');
Route::any('user/create', 'Strongadmin\User\UserController@create');
Route::any('user/update', 'Strongadmin\User\UserController@update');
Route::any('user/destroy', 'Strongadmin\User\UserController@destroy');
//文章管理
Route::any('article/article/index', 'Strongadmin\Article\ArticleController@index');
Route::any('article/article/show', 'Strongadmin\Article\ArticleController@show');
Route::any('article/article/create', 'Strongadmin\Article\ArticleController@create');
Route::any('article/article/update', 'Strongadmin\Article\ArticleController@update');
Route::any('article/article/destroy', 'Strongadmin\Article\ArticleController@destroy');
//文章分类
Route::any('article/category/index', 'Strongadmin\Article\CategoryController@index');
Route::any('article/category/show', 'Strongadmin\Article\CategoryController@show');
Route::any('article/category/create', 'Strongadmin\Article\CategoryController@create');
Route::any('article/category/update', 'Strongadmin\Article\CategoryController@update');
Route::any('article/category/destroy', 'Strongadmin\Article\CategoryController@destroy');
//意见反馈
Route::any('user/feedback/index', 'Strongadmin\User\FeedbackController@index');
Route::any('user/feedback/show', 'Strongadmin\User\FeedbackController@show');
Route::any('user/feedback/update', 'Strongadmin\User\FeedbackController@update');
Route::any('user/feedback/destroy', 'Strongadmin\User\FeedbackController@destroy');
//会员等级
Route::any('user/userRank/index', 'Strongadmin\User\UserRankController@index');
Route::any('user/userRank/show', 'Strongadmin\User\UserRankController@show');
Route::any('user/userRank/create', 'Strongadmin\User\UserRankController@create');
Route::any('user/userRank/update', 'Strongadmin\User\UserRankController@update');
Route::any('user/userRank/destroy', 'Strongadmin\User\UserRankController@destroy');
//配送方式管理
Route::any('shippingOption/index', 'Strongadmin\ShippingOptionController@index');
Route::any('shippingOption/show', 'Strongadmin\ShippingOptionController@show');
Route::any('shippingOption/create', 'Strongadmin\ShippingOptionController@create');
Route::any('shippingOption/update', 'Strongadmin\ShippingOptionController@update');
//Route::any('shippingOption/destroy', 'Strongadmin\ShippingOptionController@destroy');
//配送方式管理-配送区域
Route::any('shippingOptionConfig/index', 'Strongadmin\ShippingOptionConfigController@index');
Route::any('shippingOptionConfig/show', 'Strongadmin\ShippingOptionConfigController@show');
Route::any('shippingOptionConfig/create', 'Strongadmin\ShippingOptionConfigController@create');
Route::any('shippingOptionConfig/update', 'Strongadmin\ShippingOptionConfigController@update');
Route::any('shippingOptionConfig/destroy', 'Strongadmin\ShippingOptionConfigController@destroy');
//支付方式管理
Route::any('paymentOption/index', 'Strongadmin\PaymentOptionController@index');
Route::any('paymentOption/show', 'Strongadmin\PaymentOptionController@show');
Route::any('paymentOption/create', 'Strongadmin\PaymentOptionController@create');
Route::any('paymentOption/update', 'Strongadmin\PaymentOptionController@update');
Route::any('paymentOption/destroy', 'Strongadmin\PaymentOptionController@destroy');
//地区-国家管理
Route::any('region/regionCountry/index', 'Strongadmin\Region\RegionCountryController@index');
Route::any('region/regionCountry/show', 'Strongadmin\Region\RegionCountryController@show');
Route::any('region/regionCountry/create', 'Strongadmin\Region\RegionCountryController@create');
Route::any('region/regionCountry/update', 'Strongadmin\Region\RegionCountryController@update');
Route::any('region/regionCountry/destroy', 'Strongadmin\Region\RegionCountryController@destroy');
//地区-大陆管理
Route::any('region/regionContinent/index', 'Strongadmin\Region\RegionContinentController@index');
Route::any('region/regionContinent/show', 'Strongadmin\Region\RegionContinentController@show');
Route::any('region/regionContinent/create', 'Strongadmin\Region\RegionContinentController@create');
Route::any('region/regionContinent/update', 'Strongadmin\Region\RegionContinentController@update');
Route::any('region/regionContinent/destroy', 'Strongadmin\Region\RegionContinentController@destroy');
//网站配置
Route::any('webconfig/show', 'Strongadmin\WebconfigController@showForm');//配置详情
Route::any('webconfig/save/config', 'Strongadmin\WebconfigController@saveConfig');//保存配置
Route::any('webconfig/clearcache', 'Strongadmin\WebconfigController@clearcache');//清楚缓存
Route::any('webconfig/sendReceiveMailTest', 'Strongadmin\WebconfigController@sendReceiveMailTest');//清楚缓存
//产品评论
Route::any('product/comment/index', 'Strongadmin\Product\CommentController@index');
Route::any('product/comment/show', 'Strongadmin\Product\CommentController@show');
Route::any('product/comment/create', 'Strongadmin\Product\CommentController@create');
Route::any('product/comment/update', 'Strongadmin\Product\CommentController@update');
Route::any('product/comment/destroy', 'Strongadmin\Product\CommentController@destroy');
Route::any('product/comment/approve', 'Strongadmin\Product\CommentController@approve');
Route::any('product/comment/refused ', 'Strongadmin\Product\CommentController@refused');

routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
 */
Route::get('admin/home', function () {
    return redirect('strongadmin');
});
Route::any('/', 'HomeController@index')->name('home');
Route::get('/test', 'HomeController@test');

//登录
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login')->middleware(['guest']);
Route::post('login', 'Auth\LoginController@login');
Route::post('login/code', 'Auth\LoginController@loginCode')->middleware(['throttle:3,1']); //获取验证码
//登出
Route::get('logout', 'Auth\LoginController@logout')->name('logout');
//注册
Route::get('register', 'Auth\RegisterController@showRegisterForm')->name('register')->middleware('guest');
Route::post('register', 'Auth\RegisterController@register')->middleware(['throttle:5,1', 'guest']);
Route::get('register/captcha', 'Auth\RegisterController@captcha')->name('register.captcha');
Route::get('register/success', 'Auth\RegisterController@registerSuccess')->name('register.success');
//重置密码
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');
//确认密码
Route::get('password/confirm', 'Auth\ConfirmPasswordController@showConfirmForm')->name('password.confirm');
Route::post('password/confirm', 'Auth\ConfirmPasswordController@confirm');
//邮箱验证
Route::get('email/verify', 'Auth\VerificationController@show')->name('verification.notice');
Route::get('email/verify/{id}/{hash}', 'Auth\VerificationController@verify')->name('verification.verify');
Route::post('email/resend', 'Auth\VerificationController@resend')->name('verification.resend');
//产品列表
Route::get('product/category', 'Product\ProductController@index')->name('product.list');
Route::get('category-{catid}.html', 'Product\ProductController@index')->name('product.list.rewrite'); //url rewrite
//产品搜索
Route::get('product/search', 'Product\ProductController@search')->name('product.search');
//产品详情
Route::get('product-{id}.html', 'Product\ProductController@show')->name('product.show.rewrite'); //url rewrite
Route::get('product-{id}', 'Product\ProductController@show'); //url rewrite
Route::get('product', 'Product\ProductController@show')->name('product.show');
Route::post('product/collect', 'Product\ProductController@collect')->middleware(['auth:web']); //收藏产品
//产品评论
Route::get('comment/list', 'Product\CommentController@list')->name('comment.list');
Route::any('comment/create', 'Product\CommentController@create')->name('comment.create')->middleware(['auth:web']);
Route::post('comment/upload/picture', 'Common\UploadController@imageForWork')->middleware(['auth:web']);
Route::get('comment/search/product', 'Product\CommentController@searchProduct');
//购物车
Route::get('shoppingcart', 'Product\ShoppingCartController@showIndexForm')->name('shoppingcart'); //购物车页
Route::get('shoppingcart/fetchNavcartHtml', 'Product\ShoppingCartController@fetchShoppingcartHtml'); //顶部导航购物车html
Route::get('shoppingcart/fetchShoppingcartHtml', 'Product\ShoppingCartController@fetchShoppingcartHtml')->name('shoppingcart.fetchShoppingcartHtml'); //购物车html
Route::get('shoppingcart/products', 'Product\ShoppingCartController@products'); //购物车产品
Route::post('shoppingcart/create', 'Product\ShoppingCartController@create'); //添加/更新购物车
Route::post('shoppingcart/update', 'Product\ShoppingCartController@update'); //更新购物车
Route::post('shoppingcart/remove', 'Product\ShoppingCartController@remove'); //移除购物车产品
Route::get('shoppingcart/checkout', 'Product\CheckoutController@showIndexForm')->name('shoppingcart.checkout')->middleware('auth:web'); //结算页
Route::post('shoppingcart/checkout/createOrder', 'Product\CheckoutController@createOrder')->name('shoppingcart.createOrder')->middleware('auth:web'); //创建订单
Route::get('payment/pay', 'Payment\IndexController@index')->name('payment.pay')->middleware('auth:web');//支付
//购物车订单费用合计/总计
Route::post('shoppingcart/ordertotal', 'Product\CheckoutController@orderTotal');
//订单跟踪
Route::any('user/order/tracking', 'User\OrderController@orderTracking')->name('user.orderTracking');
//地区
Route::get('common/region/states', 'Common\RegionController@states');
//配送方式列表
Route::get('shoppingcart/shippingoptions', 'Product\CheckoutController@getShippingOptions');
//paypal 支付
Route::any('payment/paypal/return', 'Payment\PaypalController@successReturn')->name('paypal.return'); //支付成功后返回页面
Route::post('payment/paypal/notify', 'Payment\PaypalController@notify')->name('paypal.notify'); //paypal 回调
Route::get('payment/paypal/pay', 'Payment\PaypalController@payStandard')->name('paypal.pay')->middleware('auth:web'); //paypal 支付
//文章
Route::get('article/list', 'ArticleController@index')->name('article.index'); //列表
Route::get('article', 'ArticleController@show')->name('article.show'); //详情
Route::get('article-{id}.html', 'ArticleController@show')->name('article.show.rewrite');
Route::get('article/{postid}', 'ArticleController@show')->name('article.show.postid'); //根据postid唯一表示查找文章详情
//auth
Route::middleware(['auth:web'])->group(function () {
    //个人中心
    Route::get('user/index', 'User\UserController@index')->name('user.index'); //用户首页
    Route::get('user/account', 'User\UserController@account')->name('user.my.account'); //我的账号
    Route::post('user/update', 'User\UserController@update')->name('user.my.account.update'); //更新个人信息
    Route::post('user/email/resendVerify', 'User\UserController@resendEmailVerification')->middleware(['throttle:3,1']); //重新发送email验证
    Route::get('user/collects', 'User\UserController@collects')->name('user.my.collects'); //我的收藏
    Route::post('user/collects/remove', 'User\UserController@removeCollects'); //移除收藏
    //订单
    Route::get('user/orders', 'User\OrderController@orders')->name('user.my.orders'); //我的订单
    Route::get('user/order/detail', 'User\OrderController@orderDetail')->name('user.my.order.detail'); //我的订单-详情
    Route::post('user/order/cancel', 'User\OrderController@cancelOrder'); //取消订单
    Route::post('user/order/receive', 'User\OrderController@receiveOrder'); //确认收货
    //意见反馈
    Route::get('user/feedback/index', 'User\FeedbackController@index')->name('user.my.feedback'); //我的反馈
    Route::match(['get', 'post'], 'user/feedback/create', 'User\FeedbackController@create')->name('user.my.feedback.create')->middleware(['throttle:3,1']); //提交反馈
    Route::match(['get', 'post'], 'user/feedback/replies', 'User\FeedbackController@replies')->name('user.my.feedback.reylies'); //回复列表
});

Route::get('auth/facebook', 'Auth\Socialite\FacebookController@redirectToProvider')->name('auth.facebook');
Route::get('auth/facebook/callback', 'Auth\Socialite\FacebookController@handleProviderCallback')->name('auth.facebook.callback');
Route::get('auth/google', 'Auth\Socialite\GoogleController@redirectToProvider')->name('auth.google');
Route::get('auth/google/callback', 'Auth\Socialite\GoogleController@handleProviderCallback')->name('auth.google.callback');

Route::get('payment/paondelivery/pay', 'Payment\PayondeliveryController@index')->name('paondelivery.pay')->middleware('auth:web'); //货到付款

app/Models/Article.php
<?php

/**
 * StrongShop
 * @author Karen <strongshop@qq.com>
 * @license http://www.strongshop.cn/license/
 * @copyright StrongShop Software
 */

namespace App\Models;

use App\Models\Admin\Article\Article as Model;

class Article extends Model
{

    protected $appends = ['brief'];

    public function getTitleAttribute($value)
    {
        if (!$value)
        {
            return $value;
        }
        $lang_front = app('strongshop')->getCurrentLanguage();
        $arr = json_decode($value, true);
        if (!$arr)
        {
            return $value;
        }
        return $arr[$lang_front] ?? array_shift($arr);
    }

    public function getContentAttribute($value)
    {
        if (!$value)
        {
            return $value;
        }
        $lang_front = app('strongshop')->getCurrentLanguage();
        $arr = json_decode($value, true);
        if (!$arr)
        {
            return $value;
        }
        return $arr[$lang_front] ?? array_shift($arr);
    }

    public function getBriefAttribute()
    {
        $value = $this->getAttribute('content');
        $value = strip_tags($value);
        $value = mb_substr($value, 0, 100);
        return $value;
    }

}

resources/views/themes/default/user/feedback/create.blade.php
@extends('layouts.app')

@section('content')
<div class="st-user">
    <div class="st-h20"></div>
    <div class="container">
        @if (session('resent'))
        <div class="alert alert-success" role="alert">
            {{ __('A fresh verification link has been sent to your email address.') }}
        </div>
        @endif
        @if (session('verified'))
        <div class="alert alert-success" role="alert">
            {{ __('Your mailbox has been successfully verified.') }}
        </div>
        @endif
        <div class="row">
            <div class="col-xs-12 col-sm-3">
                <div class="list-group">
                    @include('layouts.includes.userMenus')
                </div>
            </div>
            <div class="col-xs-12 col-sm-9">
                <div class="panel panel-default st-user-feedback">
                    <div class="panel-body table-responsive">
                        <div class="page-header">
                            <h4>@lang('My Feedaback')</h4>
                        </div>
                        <form class="form-horizontal" method="post" id="ST-FORM" style="padding: 15px;">
                            <div class="form-group">
                                <label class="radio-inline">
                                    <input name="type" type="radio" value="1" checked=""> Buy
                                </label>
                                <label class="radio-inline">
                                    <input name="type" type="radio" value="2"> Complaint 
                                </label>
                                <label class="radio-inline">
                                    <input  name="type"type="radio" value="3"> Other
                                </label>
                            </div>
                            <div class="form-group">
                                <label for="exampleInput"></label>
                                <textarea class="form-control" rows="3" name="content" placeholder="@lang('Content')"></textarea>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary">@lang('Submit')</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="st-h20"></div>

</div>

<div class="st-h50 clearfix"></div>
@endsection
@push('scripts_bottom')
<script>
    !function () {
        $("button[type='submit']").click(function () {
            $('#ST-FORM').ajaxSubmit(function (res) {
                if (res.code !== 200) {
                    Util.showErrors(res.message);
                    return;
                }
                Util.showSuccess(res.message);
                $("#ST-FORM")[0].reset();
            });
            return false;
        });
    }
    ();
</script>
@endpush

resources/views/themes/default/user/feedback/index.blade.php
@extends('layouts.app')

@section('content')
<div class="st-user">
    <div class="st-h20"></div>
    <div class="container">
        @if (session('resent'))
        <div class="alert alert-success" role="alert">
            {{ __('A fresh verification link has been sent to your email address.') }}
        </div>
        @endif
        @if (session('verified'))
        <div class="alert alert-success" role="alert">
            {{ __('Your mailbox has been successfully verified.') }}
        </div>
        @endif
        <div class="row">
            <div class="col-xs-12 col-sm-3">
                <div class="list-group">
                    @include('layouts.includes.userMenus')
                </div>
            </div>
            <div class="col-xs-12 col-sm-9">
                <div class="panel panel-default st-user-feedback">
                    <div class="panel-body table-responsive">
                        <div class="page-header">
                            <h4>@lang('My Feedaback')</h4>
                        </div>
                        <div class="st-user-feedback-list">
                            <p><a class="btn btn-primary btn-sm"  href="{{route('user.my.feedback.create')}}">@lang('Submit New Feedback')</a></p>
                            @foreach($rows as $row)
                            <dl>
                                <dt>
                                    <a href="{{route('user.my.feedback.reylies', ['parent_id'=>$row->id])}}">
                                        @if($row->unread_replies_count>0)
                                        <span class="badge">{{$row->unread_replies_count}}</span> 
                                        @endif
                                        <font>{{$row->title}}</font>
                                    </a>
                                </dt>
                                <dd class="st-text"></dd>
                                <dd class="st-datetime">{{$row->created_at}}</dd>
                                @if($row->content_reply)
                                <dd class="st-reply">
                                    <dl>
                                        <dd class="st-text">{{$row->content_reply}}</dd>
                                        <dd class="st-datetime">{{$row->updated_at}} <strong>Admin</strong></dd>
                                    </dl>
                                </dd>
                                @endif
                            </dl>
                            @endforeach
                        </div>
                        <ul class="pager pull-left">
                            @if($rows->onFirstPage())
                            <li class="disabled"><a href="javascript:void(0)">@lang('Previous')</a></li>
                            @else
                            <li><a href="{{$rows->previousPageUrl()}}">@lang('Previous')</a></li>
                            @endif
                            @if($rows->hasMorePages())
                            <li><a href="{{$rows->nextPageUrl()}}">@lang('Next')</a></li>
                            @else
                            <li class="disabled"><a href="javascript:void(0)">@lang('Next')</a></li>
                            @endif
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="st-h20"></div>

</div>

<div class="st-h50 clearfix"></div>
@endsection

resources/views/themes/default/user/feedback/replies.blade.php
@extends('layouts.app')

@section('content')
<div class="st-user">
    <div class="st-h20"></div>
    <div class="container">
        @if (session('resent'))
        <div class="alert alert-success" role="alert">
            {{ __('A fresh verification link has been sent to your email address.') }}
        </div>
        @endif
        @if (session('verified'))
        <div class="alert alert-success" role="alert">
            {{ __('Your mailbox has been successfully verified.') }}
        </div>
        @endif
        <div class="row">
            <div class="col-xs-12 col-sm-3">
                <div class="list-group">
                    @include('layouts.includes.userMenus')
                </div>
            </div>
            <div class="col-xs-12 col-sm-9">
                <div class="panel panel-default st-user-feedback">
                    <div class="panel-body table-responsive">
                        <div class="page-header">
                            <h4>@lang('My Feedaback')</h4>
                        </div>
                        <div class="st-user-feedback-list st-user-feedback-list-replies">
                            <dl>
                                <dd class="st-datetime">{{$feedback->created_at}}</dd>
                                <dd class="st-text">{{$feedback->content}}</dd>
                            </dl>
                            @if($feedback->content_reply)
                            <dl class="st-reply">
                                <dd class="st-datetime"><strong>{{$feedback->adminUser->name ?? ''}}</strong> {{$feedback->updated_at}}</dd>
                                <dd class="st-text">{{$feedback->content_reply}}</dd>
                                <dd class="clearfix"></dd>
                            </dl>
                            @endif
                            @foreach($rows as $row)
                            @if($row->user_id === auth()->id())
                            <dl>
                                <dd class="st-datetime">{{$row->created_at}}</dd>
                                <dd class="st-text">{{$row->content}}</dd>
                            </dl>
                            @else
                            <dl class="st-reply">
                                <dd class="st-datetime"><strong>{{$row->adminUser->name ?? ''}}</strong> {{$row->created_at}}</dd>
                                <dd class="st-text">{{$row->content}}</dd>
                                <dd class="clearfix"></dd>
                            </dl>
                            @endif
                            @endforeach
                        </div>
                        @if($rows->hasPages())
                        <ul class="pager pull-left">
                            @if($rows->onFirstPage())
                            <li class="disabled"><a href="javascript:void(0)">@lang('Previous')</a></li>
                            @else
                            <li><a href="{{$rows->previousPageUrl()}}">@lang('Previous')</a></li>
                            @endif
                            @if($rows->hasMorePages())
                            <li><a href="{{$rows->nextPageUrl()}}">@lang('Next')</a></li>
                            @else
                            <li class="disabled"><a href="javascript:void(0)">@lang('Next')</a></li>
                            @endif
                        </ul>
                        @endif
                        <div class="clearfix"></div>
                        <form class="form-horizontal" method="post" id="ST-FORM" style="padding: 15px;" action="{{route('user.my.feedback.create')}}">
                            <input type="hidden" name="parent_id" value="{{$feedback->id}}" />
                            <input type="hidden" name="type" value="{{$feedback->type}}" />
                            <div class="form-group">
                                <label for="exampleInput"></label>
                                <textarea class="form-control" rows="3" name="content" placeholder="@lang('Reply content')"></textarea>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary">@lang('Submit')</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="st-h20"></div>

</div>

<div class="st-h50 clearfix"></div>
@endsection
@push('scripts_bottom')
<script>
    !function () {
        $("button[type='submit']").click(function () {
            $('#ST-FORM').ajaxSubmit(function (res) {
                if (res.code !== 200) {
                    Util.showErrors(res.message);
                    return;
                }
                Util.showSuccess(res.message, true, 1000);
                $("#ST-FORM")[0].reset();
            });
            return false;
        });
    }
    ();
</script>
@endpush